import { FastifyInstance } from 'fastify';
import { registerAlertRoutes } from './alerts.js';
import { registerDailyReportRoutes } from './dailyReports.js';
import { registerWellbeingRoutes } from './wellbeing.js';
import { registerProjectRoutes } from './projects.js';
import { registerCustomerRoutes } from './customers.js';
import { registerVendorRoutes } from './vendors.js';
import { registerEstimateRoutes } from './estimates.js';
import { registerInvoiceRoutes } from './invoices.js';
import { registerTimeEntryRoutes } from './timeEntries.js';
import { registerExpenseRoutes } from './expenses.js';
import { registerPurchaseOrderRoutes } from './purchaseOrders.js';
import { registerVendorDocRoutes } from './vendorDocs.js';
import { registerLeaveRoutes } from './leave.js';
import { registerAuthRoutes } from './auth.js';
import { registerAlertSettingRoutes } from './alertSettings.js';
import { registerApprovalRuleRoutes } from './approvalRules.js';
import { registerSendRoutes } from './send.js';
import { registerMetricJobRoutes } from './metricsJobs.js';
import { registerRecurringJobRoutes } from './recurringJobs.js';
import { registerDataQualityJobRoutes } from './dataQualityJobs.js';
import { registerReportRoutes } from './reports.js';
import { registerPdfTemplateRoutes } from './pdfTemplates.js';
import { registerTemplateSettingRoutes } from './templateSettings.js';
import { registerChatRoutes } from './chat.js';
import { registerPdfFileRoutes } from './pdfFiles.js';
import { registerSendEventRoutes } from './sendEvents.js';
import { registerScimRoutes } from './scim.js';

export async function registerRoutes(app: FastifyInstance) {
  await registerAuthRoutes(app);
  await registerAlertSettingRoutes(app);
  await registerApprovalRuleRoutes(app);
  await registerPdfTemplateRoutes(app);
  await registerTemplateSettingRoutes(app);
  await registerPdfFileRoutes(app);
  await registerSendRoutes(app);
  await registerSendEventRoutes(app);
  await registerScimRoutes(app);
  await registerMetricJobRoutes(app);
  await registerRecurringJobRoutes(app);
  await registerDataQualityJobRoutes(app);
  await registerAlertRoutes(app);
  await registerDailyReportRoutes(app);
  await registerWellbeingRoutes(app);
  await registerChatRoutes(app);
  await registerProjectRoutes(app);
  await registerCustomerRoutes(app);
  await registerVendorRoutes(app);
  await registerEstimateRoutes(app);
  await registerInvoiceRoutes(app);
  await registerTimeEntryRoutes(app);
  await registerExpenseRoutes(app);
  await registerPurchaseOrderRoutes(app);
  await registerVendorDocRoutes(app);
  await registerLeaveRoutes(app);
  await registerReportRoutes(app);
}
